### ISSUE TITLE
Compound primary keys

### ISSUE THREAD

**Issue by daurnimator** [marmelab/admin-config#69]
I'm trying to use a compound primary key.

The current code seems to expect a single field for an identifier, so I added:
```js
    RestangularProvider.addElementTransformer('users_organisation', function(element) {
        element['id'] = element.users + '/' + element.organisation
        return element;
    });
```

However, this breaks down when `users_organisation` is used as a foreign reference.

**Comment by fzaninotto** [comment]
compound primary keys are not and will not be supported.

**Comment by daurnimator** [comment]
Why not?
They are extremely common for many-many relationships.

In this case, I have a permissions matrix: users can be part of many organisations. for each organisation they can have different rights (e.g. owner vs member vs contractor). How should I represent this instead?
